version: "3"
services:
  
  webapp:
    image: urlshortener:latest
    build:
      context: .
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - redis    

  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      deploy:
        replicas: 2
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure

  app_build:
    build:
      context: .
      dockerfile: Dockerfile-Build-Application
    volumes: 
      - "./code:/application"
